apiVersion: v1
appVersion: 1.16.7-tetrate-v3
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- istiod
- istio-discovery
name: istiod
sources:
- http://github.com/istio/istio
version: 1.16.7-tetrate-v3
