apiVersion: v1
appVersion: 1.17.5-tetrate-v0
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- ingressgateway
- gateways
name: istio-ingress
sources:
- http://github.com/istio/istio
version: 1.17.5
